apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Chart.Name }}
  labels:
    name: {{ .Chart.Name }}
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: {{ .Values.kubernetesVersion }}
